# Generated by Django 4.2.13 on 2024-06-25 05:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('phone_number', models.CharField(help_text='В международном формате без знака +', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(re.compile('996(880\\d{2}|755\\d{2}|22[0-9]\\d{2}|99[9]\\d{2}|77([0-37-9]\\d{2}|5(58|9[7-9]))|(5[0157]|70)\\d{3}|54(3\\d{2}|59[5-6])|56(550|6(9\\d|47|69|8[7-9]))|20[0-35]\\d{2})\\d{4}'), 'Номер телефона должен соответствовать формату Кыргызской Республики без знака +')], verbose_name='Номер телефона')),
                ('trainertg_id', models.CharField(blank=True, help_text='Заполнять не нужно', max_length=16, null=True, unique=True, verbose_name='Telegram ID тренера')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Занятие')),
                ('start_date', models.DateField(verbose_name='Дата начала занятий')),
                ('end_date', models.DateField(verbose_name='Дата конца занятий')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to', models.PositiveSmallIntegerField(verbose_name='Количество участников до включительно')),
                ('price_to', models.PositiveIntegerField(verbose_name='Цена до')),
                ('quantity_from', models.PositiveSmallIntegerField(verbose_name='Количество участников от включительно')),
                ('price_from', models.PositiveIntegerField(verbose_name='Цена от')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество участников')),
                ('recording_day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('recording_date', models.DateField(verbose_name='Дата записи')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
            },
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала занятия')),
                ('end_time', models.TimeField(verbose_name='Время конца занятия')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='training.training', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Расписание занятия',
                'verbose_name_plural': 'Расписания занятий',
                'unique_together': {('training', 'day_of_week', 'start_time')},
            },
        ),
    ]
