# Generated by Django 4.2.13 on 2024-09-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_rename_trainertg_id_trainer_tg_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingschedule',
            unique_together={('training', 'day_of_week', 'start_time')},
        ),
    ]
